# Generated by Django 5.1.1 on 2024-09-10 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GenralAdministration", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mannegare",
            options={"verbose_name": "Mannegare", "verbose_name_plural": "Mannegares"},
        ),
    ]
