# Generated by Django 5.1.1 on 2024-12-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GenralAdministration", "0003_activitylog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitylog",
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
            },
        ),
    ]
