# Generated by Django 5.1.1 on 2024-12-23 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CommercialManagement", "0002_alter_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="CM_EmployeeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=150)),
                (
                    "national_id",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(14)],
                    ),
                ),
                ("email", models.EmailField(max_length=245, unique=True)),
                ("phone_number1", models.CharField(max_length=13, unique=True)),
                (
                    "phone_number2",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                ("graduation_date", models.DateField()),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("high_school", "High School"),
                            ("bachelor", "Bachelor"),
                            ("master", "Master"),
                            ("doctorate", "Doctorate"),
                        ],
                        default="high_school",
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")],
                        default="male",
                        max_length=6,
                    ),
                ),
                ("year_of_birth", models.DateField()),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "single"),
                            ("married", "married"),
                            ("divorced", "divorced"),
                            ("widowed", "widowed"),
                        ],
                        default="single",
                        max_length=10,
                    ),
                ),
                ("employment_date", models.DateField(auto_now_add=True)),
                (
                    "job_title",
                    models.CharField(
                        choices=[
                            ("HR_MANAGER", "HR Manager"),
                            ("TEAM_LEADER", "Team Leader"),
                            ("SALES_MANAGER", "Sales Manager"),
                            ("MARKETING_MANAGER", "Marketing Manager"),
                            ("CUSTOMER_SERVICE_REP", "Customer Service Representative"),
                            ("PROCUREMENT_MANAGER", "Procurement Manager"),
                            ("FINANCIAL_ANALYST", "Financial Analyst"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "CM_Employee",
                "verbose_name_plural": "CM_Employees",
            },
        ),
    ]
