# Generated by Django 5.1.1 on 2025-03-02 18:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CommercialManagement", "0003_cm_employeemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Campaign Name"),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Budget"
                    ),
                ),
                ("description", models.TextField()),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Enter discount percentage (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Discount (%)",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("status", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
            },
        ),
        migrations.CreateModel(
            name="CampaignTargetModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="CommercialManagement.campaignmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Target",
                "verbose_name_plural": "Campaign Targets",
            },
        ),
        migrations.CreateModel(
            name="DataAnalysisEmployeeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=150)),
                (
                    "national_id",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(14)],
                    ),
                ),
                ("email", models.EmailField(max_length=245, unique=True)),
                ("phone_number1", models.CharField(max_length=13, unique=True)),
                (
                    "phone_number2",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                ("graduation_date", models.DateField()),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("high_school", "High School"),
                            ("bachelor", "Bachelor"),
                            ("master", "Master"),
                            ("doctorate", "Doctorate"),
                        ],
                        default="high_school",
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")],
                        default="male",
                        max_length=6,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "single"),
                            ("married", "married"),
                            ("divorced", "divorced"),
                            ("widowed", "widowed"),
                        ],
                        default="single",
                        max_length=10,
                    ),
                ),
                ("employment_date", models.DateField(auto_now_add=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Data Analyst", "Data Analyst"),
                            (
                                "Business Intelligence Specialist",
                                "Business Intelligence Specialist",
                            ),
                            ("Reporting Specialist", "Reporting Specialist"),
                            ("Database Administrator", "Database Administrator"),
                            ("HR Specialist", "HR Specialist"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Analysis Employee",
                "verbose_name_plural": "Data Analysis Employees",
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Amount"),
                            ("percentage", "Percentage"),
                        ],
                        default="percentage",
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Discount Value",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="CommercialManagement.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discount",
                "verbose_name_plural": "Discounts",
            },
        ),
        migrations.CreateModel(
            name="MarktingEmployeeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=150)),
                (
                    "national_id",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(14)],
                    ),
                ),
                ("email", models.EmailField(max_length=245, unique=True)),
                ("phone_number1", models.CharField(max_length=13, unique=True)),
                (
                    "phone_number2",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                ("graduation_date", models.DateField()),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("high_school", "High School"),
                            ("bachelor", "Bachelor"),
                            ("master", "Master"),
                            ("doctorate", "Doctorate"),
                        ],
                        default="high_school",
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")],
                        default="male",
                        max_length=6,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "single"),
                            ("married", "married"),
                            ("divorced", "divorced"),
                            ("widowed", "widowed"),
                        ],
                        default="single",
                        max_length=10,
                    ),
                ),
                ("employment_date", models.DateField(auto_now_add=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Marketing Manager", "Marketing Manager"),
                            (
                                "Digital Marketing Specialist",
                                "Digital Marketing Specialist",
                            ),
                            ("Content Creator", "Content Creator"),
                            ("SEO Specialist", "SEO Specialist"),
                            ("HR Specialist", "HR Specialist"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Markting Employee",
                "verbose_name_plural": "Markting Employees",
            },
        ),
        migrations.CreateModel(
            name="PriceManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Base Price"
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Date when this price becomes effective",
                        verbose_name="Effective Date",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="CommercialManagement.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Management",
                "verbose_name_plural": "Price Managements",
            },
        ),
        migrations.CreateModel(
            name="PricingEmployeeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=150)),
                (
                    "national_id",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(14)],
                    ),
                ),
                ("email", models.EmailField(max_length=245, unique=True)),
                ("phone_number1", models.CharField(max_length=13, unique=True)),
                (
                    "phone_number2",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                ("graduation_date", models.DateField()),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("high_school", "High School"),
                            ("bachelor", "Bachelor"),
                            ("master", "Master"),
                            ("doctorate", "Doctorate"),
                        ],
                        default="high_school",
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")],
                        default="male",
                        max_length=6,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "single"),
                            ("married", "married"),
                            ("divorced", "divorced"),
                            ("widowed", "widowed"),
                        ],
                        default="single",
                        max_length=10,
                    ),
                ),
                ("employment_date", models.DateField(auto_now_add=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Pricing Manager", "Pricing Manager"),
                            ("Promotions Manager", "Promotions Manager"),
                            ("Campaign Coordinator", "Campaign Coordinator"),
                            ("Market Research Analyst", "Market Research Analyst"),
                            ("HR Specialist", "HR Specialist"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing Employee",
                "verbose_name_plural": "Pricing Employees",
            },
        ),
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_quantity",
                    models.PositiveIntegerField(verbose_name="Minimum Quantity"),
                ),
                (
                    "max_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Maximum Quantity"
                    ),
                ),
                (
                    "discounted_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Discounted Price"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_rules",
                        to="CommercialManagement.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing Rule",
                "verbose_name_plural": "Pricing Rules",
            },
        ),
        migrations.CreateModel(
            name="ProcurementEmployeeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=150)),
                (
                    "national_id",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(14)],
                    ),
                ),
                ("email", models.EmailField(max_length=245, unique=True)),
                ("phone_number1", models.CharField(max_length=13, unique=True)),
                (
                    "phone_number2",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                ("graduation_date", models.DateField()),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("high_school", "High School"),
                            ("bachelor", "Bachelor"),
                            ("master", "Master"),
                            ("doctorate", "Doctorate"),
                        ],
                        default="high_school",
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")],
                        default="male",
                        max_length=6,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "single"),
                            ("married", "married"),
                            ("divorced", "divorced"),
                            ("widowed", "widowed"),
                        ],
                        default="single",
                        max_length=10,
                    ),
                ),
                ("employment_date", models.DateField(auto_now_add=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Procurement Manager", "Procurement Manager"),
                            ("Procurement Officer", "Procurement Officer"),
                            ("Vendor Relations Manager", "Vendor Relations Manager"),
                            ("Inventory Coordinator", "Inventory Coordinator"),
                            ("HR Specialist", "HR Specialist"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Procurement Employee",
                "verbose_name_plural": "Procurement Employees",
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Promotion Name"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "min_quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Minimum Quantity Required"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="CommercialManagement.discount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion",
                "verbose_name_plural": "Promotions",
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Item Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Unit Price"
                    ),
                ),
                (
                    "order_date",
                    models.DateField(auto_now_add=True, verbose_name="Order Date"),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expected Delivery Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("received", "Received"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_items",
                        to="CommercialManagement.supplier",
                        verbose_name="Supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesEmployeeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=150)),
                (
                    "national_id",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(14)],
                    ),
                ),
                ("email", models.EmailField(max_length=245, unique=True)),
                ("phone_number1", models.CharField(max_length=13, unique=True)),
                (
                    "phone_number2",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                ("graduation_date", models.DateField()),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("high_school", "High School"),
                            ("bachelor", "Bachelor"),
                            ("master", "Master"),
                            ("doctorate", "Doctorate"),
                        ],
                        default="high_school",
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")],
                        default="male",
                        max_length=6,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "single"),
                            ("married", "married"),
                            ("divorced", "divorced"),
                            ("widowed", "widowed"),
                        ],
                        default="single",
                        max_length=10,
                    ),
                ),
                ("employment_date", models.DateField(auto_now_add=True)),
                (
                    "job_title",
                    models.CharField(
                        choices=[
                            ("HR_MANAGER", "HR Manager"),
                            ("HR_SPECIALIST", "HR Specialist"),
                            ("TEAM_LEADER", "Team Leader"),
                            ("SALES_MANAGER", "Sales Manager"),
                            ("SALES_REPRESENTATIVE", "Sales Representative"),
                            ("MARKETING_MANAGER", "Marketing Manager"),
                            ("MARKETING_SPECIALIST", "Marketing Specialist"),
                            ("CUSTOMER_SERVICE_REP", "Customer Service Representative"),
                            ("PROCUREMENT_MANAGER", "Procurement Manager"),
                            ("FINANCIAL_ANALYST", "Financial Analyst"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "CM_Employee",
                "verbose_name_plural": "CM_Employees",
            },
        ),
        migrations.DeleteModel(
            name="CM_EmployeeModel",
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="CommercialManagement.supplier",
            ),
        ),
        migrations.AddField(
            model_name="campaignmodel",
            name="marketer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="CommercialManagement.marktingemployeemodel",
                verbose_name="Marketer",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="procurement_employee",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="CommercialManagement.procurementemployeemodel",
                verbose_name="Procurement Employee",
            ),
        ),
    ]
